<?php

/**
 * @file mbc_faq.module
 */

/**
 * Implements hook_theme().
 */
function mbc_faq_theme($existing, $type, $theme, $path) {
  return [
    'mbc_faq__list_page' => [
      'variables' => [
        'links' => [],
        'list' => [],
        'pager' => ''
      ],
    ],
    'mbc_faq__list_item' => [
      'variables' => [
        'id' => '',
        'question' => '',
        'answer' => '',
        'group' => '',
        'author' => '',
        'links' => [],
      ],
    ],
  ];
}
